### ISSUE TITLE
Is there a way to change hair color?

### ISSUE THREAD

**Issue by JamesKrolak** [BarleyFlour/VisualAdjustments2#18]
Is there a way to change hair color after you've chosen the hair option from a different race using the EE Picker?  Unless I was doing it wrong, I wasn't seeing a way to do that.

**Comment by Walters-Marissa** [comment]
this shit is a buggy mess and much less effective than the  previous version, which could be fixed with a simple hotkey most of the time, you have to constantly reload the visual page and try and get the picker to recognize the item can be colored and then color it, even coloring it sometimes must be done multiple times because it doesn't take.  some hair colors might not be colorable, though all the base ones should be.

**Comment by JamesKrolak** [comment]
For those like me that are a bit slow on the uptake, you can color most items but you have to select it (in this case, the hair object) on the left hand side, then click the color picking icon in the lower right to color that specific item.  Some items cannot be colored 'cuz they're set pieces in the game.  And if you play with a lot of stuff in a single session, it can get to the point where nothing will change color.  If that happens, exit the screens for the mod and then go back in and it usually starts working again.
